version: '2'
services:
  tiendadevideojuegos-app:
    image: tiendadevideojuegos
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tiendadevideojuegos-postgresql:5432/TIendaDeVideoJuegos
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  tiendadevideojuegos-postgresql:
    extends:
      file: postgresql.yml
      service: tiendadevideojuegos-postgresql
